
# DL Assignment 03

**Name:** Maria Akter Mukti

**Course Email:**  mariamukti051@gmail.com


## End of Assignment

Before submitting:
- Run all cells from top to bottom.  
- Check that all answer sections are filled.  
- Instruction video অনুযায়ী আমাদের দেয়া Colab ফাইলটি থেকে প্রথম একটি Save copy in drive করে নিবা। এরপর Google colab এর মধ্যে কোডগুলো করবে এবং সেই ফাইলটি ‘Anyone with the link’ & ‘View’ Access দিয়ে ফাইলটির Shareble Link টি সাবমিট করবে।

# General Instruction

You must choose your own dataset.

The dataset must:

Be a supervised learning dataset (Regression or Binary Classification)

Contain at least 300 samples

Have at least 2 input features

Be in CSV format

You are NOT allowed to use Dataset or DataLoader.

You must implement everything manually.

# Question 01: [ Marks 05 ]

## Dataset Preparation

## Using your chosen dataset:

Load the dataset.

Perform necessary preprocessing:

Handle missing values (if any)

Encode categorical variables (if necessary)

Feature scaling (if needed)

Separate features (X) and target (y).

Convert them into NumPy arrays.

Convert them into PyTorch tensors.

Split into training and testing sets.

Clearly explain each preprocessing decision.

# **Write** Answer 01:

In [73]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("cyberbullying_dataset_1000 (1).csv")
df.head()

Saving cyberbullying_dataset_1000.csv to cyberbullying_dataset_1000 (4).csv

,post_id,user_id,text,label,post_length,avg_sentiment,num_likes,num_shares,num_reports,user_posts,user_friends,response_time,toxicity_score
0,p0001,u101,Wishing you all the best in your exams.,non-bullying,8,0.47,69,20,0,169,326,3.82,0.12
1,p0002,u102,"You’re a joke, nobody cares about you.",bullying,7,-0.99,5,1,4,439,107,3.96,0.88
2,p0003,u103,"Happy birthday, hope you have a wonderful day!",non-bullying,8,0.50,84,8,0,172,310,0.74,0.03
3,p0004,u104,"Just disappear, nobody will miss you.",bullying,6,-0.76,5,2,1,180,23,4.03,0.99
4,p0005,u105,Wishing you all the best in your exams.,non-bullying,8,0.35,38,13,0,484,761,1.36,0.18

In [74]:
#Check missing
df.isnull().sum()

post_id           0
user_id           0
text              0
label             0
post_length       0
avg_sentiment     0
num_likes         0
num_shares        0
num_reports       0
user_posts        0
user_friends      0
response_time     0
toxicity_score    0
dtype: int64

There were no missing values in the dataset. no modification needed

In [75]:
df = df.drop(['post_id', 'user_id', 'text'], axis=1)

remove them for better and fast work. because they dont help to predict.

In [76]:
#encode
df['label'] = df['label'].apply(lambda x: 1 if x == 'bullying' else 0)

here, bullying = 1

non-bullying = 0

In [77]:
#Separate features (X) and target (y).
X = df[['post_length', 'avg_sentiment', 'num_reports', 'toxicity_score']]
y = df['label']

In [78]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

In [79]:
#convert to numpy
import numpy as np

X = np.array(X)
y = np.array(y)

In [80]:
#Convert to torch
import torch

X_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.float32).view(-1, 1)

In [81]:
#train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_tensor, y_tensor, test_size=0.2, random_state=42
)

print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

Training shape: torch.Size([800, 4])
Testing shape: torch.Size([200, 4])

80% training ->  model learning

20% testing ->  model evaluation

# Question 02: [ Marks 20 ]

## Design a neural network using nn.Module.

### The model must contain:

Input layer

At least one hidden layer

Output layer

Suitable activation function



## Justify:

Number of hidden neurons

Choice of activation function

Print  the total number of trainable parameters.

## Write Answer 02:

In [82]:
import torch
import torch.nn as nn

In [83]:
class CyberBullyingNN(nn.Module):
    def __init__(self):
        super(CyberBullyingNN, self).__init__()

        # Input layer
        self.fc1 = nn.Linear(4, 8)   # hidden
        self.fc2 = nn.Linear(8, 1)   # output

        # Activationfunction
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)   # hidden activation
        x = self.fc2(x)
        x = self.sigmoid(x)  # binary output
        return x

In [84]:
#model creation
model = CyberBullyingNN()
print(model)

CyberBullyingNN(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=1, bias=True)
  (relu): ReLU()
  (sigmoid): Sigmoid()
)

In [85]:
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print("Total parameters:", total_params)

Total parameters: 49

Input features: 4

Hidden layer: 8 neurons

Output layer: 1 neuron


Activation Functions:

Hidden layer: ReLU cz non-linearity, fast learning
Output layer: Sigmoid cz it gives probability between 0 and 1

Parameter Calculation:

Layer 1 :

W: 4 * 8 = 32

B: 8

Total = 32 + 8 = 40

----

Layer 2:

W: 8 * 1 = 8

B: 1

Total = 8 + 1 = 9

-----

Total Trainable Parameters =  40 + 9 = 49 parameters

# Question 03: [ Marks 10 ]

Choose an appropriate loss function.

Choose an optimizer.

<br>

Justify your choices based on:

Regression vs Classification

Nature of the dataset

## Write Answer 03:

In [86]:
import torch.nn as nn

loss = nn.BCELoss()

This problem is a Binary Classification problem.
here,

bullying -> 1

non-bullying -> 0

In [87]:
import torch.optim as optim

optimizer = optim.Adam(model.parameters(), lr=0.001)

Based on Nature of Dataset:

Dataset size  1000 samples, not big. it is small or medium.

Features are simple numeric values

so, We need:

-> Fast training

-> Stable learning

That is why, Adam is suitable for this. cz, it automatically adjusts learning rate, it also works well without heavy tuning and easily handle small dataset.

# Question 04: [ Marks 15 ]

## Implement a full training loop:

Forward pass

Loss computation

Backward pass

Parameter update

Gradient reset

### Requirements:

Train for at least 100 epochs.

Print loss every 10 epochs.

Store training loss history(You can pick your own Data Structure).

Explain clearly what happens in each step of the pipeline.

## Write Answer 04:

In [94]:
epochs = 100
loss_history = []

for epoch in range(epochs):

    # Forward Pass
    y_pred = model(X_train)

    # Loss Computation
    current_loss = loss(y_pred, y_train)

    # backward Pass
    current_loss.backward()

    # Parameter Update
    optimizer.step()

    # Gradient reset
    optimizer.zero_grad()

    # Store loss
    loss_history.append(current_loss.item())

    # Print every 10 epochs
    if epoch % 10 == 0:
        print("Epoch:", epoch, "Loss:", current_loss.item())

Epoch: 0 Loss: 0.3381437659263611
Epoch: 10 Loss: 0.31701186299324036
Epoch: 20 Loss: 0.2967081367969513
Epoch: 30 Loss: 0.2773275673389435
Epoch: 40 Loss: 0.2589615285396576
Epoch: 50 Loss: 0.24167776107788086
Epoch: 60 Loss: 0.22548870742321014
Epoch: 70 Loss: 0.21036767959594727
Epoch: 80 Loss: 0.19626562297344208
Epoch: 90 Loss: 0.18312746286392212

Loss is decreasing steadily, so model is learning properly, stable convergence

1. Forward Pass:

We give input data to the model, and it passes through the network to produce a prediction.


2. Loss Computation:

This tells us how wrong the model is.

3. Backward Pass:

This helps the model understand how to improve.

4. Parameter Update:

Because of updation the model learns and try to be more better.

5. Gradient Reset:
It keeps learning clean and correct.

6. Loss Storage:

We save the loss from each epoch in a list.


7. Printing Loss:

Every 10 epochs, we print the loss to check progress.
It is what how we can track if the model is actually learning.

# Question 05: [ Marks 10 ]

## Evaluate the model on test data.

## For regression:

Report MSE and MAE


## For classification:

Report Accuracy

Compare training vs testing performance.

State whether the model is underfitting or overfitting.

## Write Answer 05:

In [101]:
from sklearn.metrics import accuracy_score

# Forward pass on test data
y_test_pred = model(X_test)

y_test_pred_class = (y_test_pred > 0.5).float()

# Accuracy
accuracy = accuracy_score(y_test, y_test_pred_class)

print("Test Accuracy:", accuracy)

Test Accuracy: 1.0

In [103]:
y_train_pred = model(X_train)
y_train_pred_class = (y_train_pred > 0.5).float()

train_accuracy = accuracy_score(y_train, y_train_pred_class)

print("Train Accuracy:", train_accuracy)

Train Accuracy: 1.0

Report Accuracy:

Train Accuracy: 1

Test Accuracy: 1
----------------

Compare training vs testing performance:

Train and test accuracy are same.
This shows stable and consistant performance.

-----------

The model is not underfitting cz accuracy is high

The model is not overfitting cz no big gap between train and test.

So, the model has good generalization.

# Question 06: [ Marks 20 ]

## Modify at least ONE of the following:

Learning rate

Number of hidden neurons

Number of epochs

### Train again and compare:

Convergence speed

Final performance

Explain how the change affected the model.

## Write Answer 06:

In [97]:
class CyberBullyingNN_Modified(nn.Module):
    def __init__(self):
        super(CyberBullyingNN_Modified, self).__init__()

        # Increased hidden neurons (8 → 16)
        self.fc1 = nn.Linear(4, 16)
        self.fc2 = nn.Linear(16, 1)

        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.sigmoid(x)
        return x

model2 = CyberBullyingNN_Modified()

In [98]:
epochs = 100
loss_history2 = []

for epoch in range(epochs):

    y_pred = model2(X_train)
    current_loss = loss(y_pred, y_train)

    current_loss.backward()
    optimizer2 = torch.optim.Adam(model2.parameters(), lr=0.001)
    optimizer2.step()
    optimizer2.zero_grad()

    loss_history2.append(current_loss.item())

    if epoch % 10 == 0:
        print("Epoch:", epoch, "Loss:", current_loss.item())

Epoch: 0 Loss: 0.8554055690765381
Epoch: 10 Loss: 0.8078618049621582
Epoch: 20 Loss: 0.7632067203521729
Epoch: 30 Loss: 0.7212982773780823
Epoch: 40 Loss: 0.6817348003387451
Epoch: 50 Loss: 0.6445336937904358
Epoch: 60 Loss: 0.6097115874290466
Epoch: 70 Loss: 0.5772228240966797
Epoch: 80 Loss: 0.5468839406967163
Epoch: 90 Loss: 0.518197774887085

Original Model:

Faster convergence, and lower loss in fewer epochs

------

Modified Model:

Slower convergence, more gradual learning

------

Final Performance:

Original model performs better on this dataset.

Modified model did not improve accuracy significantly.

So, increased neurons made training more complex without benefit

-------

Increasing hidden neurons from 8 -> 16 did not improve performance in this case.
The original model was already sufficient for the dataset.

# Question 07: [ Marks 20 ]


# Training Analysis

Answer the following:

Why must gradients be reset every epoch?

What happens if learning rate is too high?

What happens if learning rate is too small?

Why do we define layers inside the constructor (__init__) and not inside forward()?

## Write Answer 07:

Why must gradients be reset every epoch?

Because gradients accumulate in PyTorch.
If not reset, old gradients will mix with new ones and give wrong updates.

---

What happens if learning rate is too high?

Model updates become too big.
Loss can be unstable, and can't give proper learning rate at all.

-----

What happens if learning rate is too small?

Model will learns very slowly.
Takes too many epochs to converge. and will be more late for a better performnce.

---

Why define layers in __init__ not in forward()?

__init__ creates layers once.
forward() only uses them for computation.
If defined in forward(), layers reset every time -> as a result, model can't learn properly.